# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
   config.vm.box = "centos01"
   config.vm.network "private_network", ip: "192.168.3.2"
   config.vm.network "forwarded_port", guest: 3000, host: 8000
   config.vm.synced_folder "/Users/llavina/Documents/my_repos/vmachines/newvm/shared/salt", "/srv/salt/"
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = false
     vb.memory = "1024"
   end  
   #config.vm.provision :salt do |salt|
   #  salt.masterless = true
   #  salt.minion_config = "shared/minion"
   #  salt.run_highstate = true
   #end
end
